### ISSUE TITLE
Webpack está dando erro

### ISSUE THREAD

**Issue by roger-av13** [rocketseat-education/curso-es6#5]
Olá, tudo bem? 

estou tendo dificuldade de configurar o webpack mesmo com curso anda dando erro e não sei como resolver, algum pode me ajudar?

este é erro,

C:\CURSO\curso_ES6\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

ReferenceError: modules is not defined
    at Object.<anonymous> (C:\CURSO\curso_ES6\webpack.config.js:1:63)
    at Module._compile (C:\CURSO\curso_ES6\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (C:\CURSO\curso_ES6\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (C:\CURSO\curso_ES6\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (C:\CURSO\curso_ES6\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at C:\CURSO\curso_ES6\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\CURSO\curso_ES6\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at C:\CURSO\curso_ES6\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (C:\CURSO\curso_ES6\node_modules\yargs\yargs.js:567:18)
    at C:\CURSO\curso_ES6\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\CURSO\curso_ES6\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\CURSO\curso_ES6\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11

**Comment by danielconan** [comment]
Conseguiu Resolver o Erro?

**Comment by roger-av13** [comment]
Olá Daniel, não consegui, nem prosseguir no curso por causa desse erro

**Comment by roger-av13** [comment]
Se alguém da rocket puder me ajudar

**Comment by danielconan** [comment]
Boa tarde Rogério!

Sou iniciante tb no Curso da Rockeat !

Mas se quiser add meu contato, meu Whatsapp é : 11 957967185

Em sex, 10 de jul de 2020 10:27, Rogério Vieira <notifications@github.com>
escreveu:
